export enum Provincias {
    'Ciudad Autónoma de Buenos Aires',
    'Neuquén',
    'San Luis',
    'Santa Fe',
    'La Rioja',
    'Catamarca',
    'Tucumán',
    'Chaco',
    'Formosa',
    'Santa Cruz',
    'Chubut',
    'Mendoza',
    'Entre Ríos',
    'San Juan',
    'Jujuy',
    'Santiago del Estero',
    'Río Negro',
    'Corrientes',
    'Misiones',
    'Salta',
    'Córdoba',
    'Buenos Aires',
    'La Pampa',
    'Tierra del Fuego, Antártida e Islas del Atlántico Sur'
}
